### ISSUE TITLE
师傅，这个css具体指定是什么，有些站找不到唯一属性值，在脚本里加了type，但是运行不了

### ISSUE THREAD

**Issue by able9527** [winezer0/Browser-Brute#1]
比如这种站点
![image](https://user-images.githubusercontent.com/59350511/169636071-f6c2c690-60ca-4a45-a235-43009c5d2c6c.png)

改了部分脚本
![image](https://user-images.githubusercontent.com/59350511/169635968-09b422d8-6855-4c28-ae85-9965a64fc46b.png)
![image](https://user-images.githubusercontent.com/59350511/169635982-7ab9c93b-ccac-4c6d-acb1-f6c87627b84e.png)
但是还是异常退出
![image](https://user-images.githubusercontent.com/59350511/169636016-005de891-bd06-48d7-a941-fcf8ca1f7f12.png)

**Comment by able9527** [comment]
![image](https://user-images.githubusercontent.com/59350511/169636048-9bac43a8-ffa4-46c1-89cd-1f514abec63a.png)
就是这种站点

**Comment by winezer0** [comment]
抱歉抱歉，这个type是开发测试遗留

**Comment by winezer0** [comment]
看了一下代码，没有by_type这个参数呀

**Comment by winezer0** [comment]
这个css选择比较麻烦，要知道css查询语法才行。

**Comment by winezer0** [comment]
Selenium之find_element_by_css_selector()的使用方法
https://blog.csdn.net/qq_35861801/article/details/108125082
